version: "3.2"

services:
    keycloak:
        image: jboss/keycloak:10.0.2
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin123
            - DB_VENDOR=mssql
            - DB_PASSWORD=Password123!
            - DB_ADDR=127.0.0.1
            - DB_DATABASE=Keycloak

    mssql:
        image: mssql-keycloak
        ports:
            - "1433:1433"
        #entrypoint: ./setup-keycloak-db-entrypoint.sh
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password123!
