# Pushes non-master branch changes to https://draft.rootisgod.com/

name: Octopus-DeploymentPipelineProject-Terraform-Deployment

# Controls when the action will run.
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/iaingblack/deploymentpipeline-deployer:2021-06-26

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Terraform Deploy
              run: |
                  export TF_VAR_octopus_api_key="${{ secrets.Octopus_Cloud_API_Key }}"
                  cd DeploymentPipeline//OctopusTerraform/DeploymentPipelineProject/
                  terraform init
                  terraform plan
                  terraform apply -auto-approve
