# Pushes non-master branch changes to https://draft.rootisgod.com/

name: Octopus-DeploymentPipelineProject-Terraform-Deployment

# Controls when the action will run.
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        # https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/iaingblack/deploymentpipeline-deployer:2021-06-26
            credentials:
              username: ${{ github.actor }}
              password: ${{ secrets.PAT }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

#             # Login against a Docker registry except on PR
#             # https://github.com/docker/login-action
#             - name: Log into registry ${{ env.REGISTRY }}
#               if: github.event_name != 'pull_request'
#               uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
#               with:
#                 registry: ${{ env.REGISTRY }}
#                 username: ${{ github.actor }}
#                 password: ${{ secrets.PAT }}

            - name: Terraform Deploy
              run: |
                  export TF_VAR_octopus_api_key="${{ secrets.Octopus_Cloud_API_Key }}"
                  cd DeploymentPipeline//OctopusTerraform/DeploymentPipelineProject/
                  terraform init
                  terraform plan
                  terraform apply -auto-approve
